# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e223f4f81365a491b28ef1b614507270c9ae0d825dc72d028e3925267db0380f944aaa4aeb2f2da6f795088bdaecbb96a6942796aee0037bacf6ddb7998928a

test:
  secret_key_base: f32618352519fd2daeb73ba6c80a300efd1a4593fca4332900d1e8b11e9489e52dd9e53d93e56bc196e5bb15442a7443ecf76d8b8e4b6767270f375f075ae79f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
